migen/fhdl/bitcontainer.py
This is clearly a bug; it fails whenever the bit-width of the output of a multiplication is needed. In my case that was slicing such an output.
=> fixed bug in value_bits_sign of mul operatiors

migen/fhdl/structure.py
Set the width and signedness, when an integer or boolean is given as the reset value.
=> Set the width and signedness of the reset value.

migen/fhdl/structure.py
Fixes #66 issue which resulted in creation of redundant clock domains
=> Implement __contains__() method for _ClockDomainList class

migen/fhdl/structure.py, migen/fhdl/tools.py
The synchronous reset logic has been rewritten from
`if (rst) <rst> else <code>`
to
`<code> if (rst) <rst>`
=> support reset-less Signals (closes #54)

migen/genlib/fifo.py
There's a 'width' attribute -- so why no 'depth', too?
=> Add 'depth' attribute to _FIFOInterface

migen/build/lattice/programmer.py, migen/build/platforms/tinyfpga_b.py
[TinyFPGA B2](http://tinyfpga.com) is an Ice40-based FPGA board in a 28-pin breadboard-friendly form factor. It contains a minimum of peripherals, mainly deferring I/O to headers, but is notable for exposing a USB port as I/O. The official repository provides [a reference design](https://github.com/tinyfpga/TinyFPGA-B-Series/tree/master/bootloader) implementing a USB device.
This PR depends on #84 being merged first to actually function, but since both PRs are ready and don't conflict, I figured I'd open this one in parallel.
=> Add TinyFPGA B Platform

migen/test/test_platform.py
This PR adds `test_platform.py` to the unit tests. The new module recursively collects all supported platforms, creates a dummy `Module` for each platform, and ensures the output files for building with a toolchain are successfully generated.
Ideally, I would prefer to exercise `GenericPlatform.request()` functionality in `TestModulePlatform`, but I haven't figured out a clean way to probe available I/O and choose two (without making tests nondeterministic). Additionally `test_roach` is going to fail b/c there is no default clock, but as I suspect that is by design, I think it's acceptable.
=> Add Platform-specific tests

migen/build/platforms/de0nano.py
This was incorrectly listed as T9 but should be T8. See pg14 of the user manual, ftp://ftp.altera.com/up/pub/Intel_Material/Boards/DE0-Nano/DE0_Nano_User_Manual.pdf
=> build/platforms/de0nano: Fix incorrect sw1 pin assignment: T9->T8

migen/genlib/fifo.py
When using SyncFIFO with fwft=False, the memory location corresponding to the last data read is vacated. When the fifo reaches capacity, the data is overwritten and the output changes to the last data written after 1 cycle.
Change the memory mode to register the output data (rather than the output address) so data read remains valid even when fifo is full.
=> fix data output changing while not reading when fifo is full in non-fwft mode

migen/fhdl/verilog.py
Currently the emitted verilog for signed constants always has 2**nbits added, which means for nonnegative values it will exceed the maximum value for its bit width. Since this just truncates it's not a problem, but it leads to thousands of pointless warnings in Quartus.
Not sure if you care especially about trying to quiet unnecessary warnings but it's a quick change to do so.
=> fhdl/verilog: Don't emit constants larger than bit width for signed constants

migen/build/platforms/mercury.py
One of my first commits to Migen was to add the [Mercury](https://www.micro-nova.com/mercury) FPGA development board as a platform. About the same time I did, a peripheral for Mercury known as the [Baseboard](https://www.micro-nova.com/mercury-baseboard) was released. Not having a Baseboard, I put adding support as a TODO until I got one.
Well I got one pretty soon after that commit, and only _now_ have I gotten around to adding support for the Baseboard in Migen :).
This PR is noninvasive, but I did run into an issue wrt constraints: Baseboard has a PMOD connector, and normally in Migen I see this provided as a connector with a user needs to modify w/ `add_extension`. In the case of Mercury, whose GPIO pins can be used standalone or with the Baseboard, the PMOD connector overlaps with …
=> Add Mercury Baseboard support

migen/fhdl/simplify.py
Migen simulation behavior of read-only ports in `WRITE_FIRST` (default) mode does not correspond to the behavior of the emitted verilog translation; instead they behave like `READ_FIRST` ports.
In case of address collision, or (if a read enable signal is used on the read port) in case of later modification of the read memory location, the output value changes in synthesis but does not change in simulation.
This makes sure that read-only ports in `WRITE_FIRST` mode fall into the same case as they do in synthesis.
The simulation code for `NO_CHANGE` mode uses the `port.we` signal and reduces to the else condition when the port is read-only, so no change needed there.
=> make memory simulation behavior for read ports same as emitted verilog

migen/fhdl/tracer.py
Self-explanatory. Tested using Cygwin (patched with to-be-merged #88).
=> fhdl/tracer: Add guard code to support Python 3.6. Closes #62.

migen/build/lattice/icestorm.py
IceStorm tools now have support for the iCE40-UP5K-SG48.  This adds the options for the UP5K device in migen/build.
=> Lattice UP5K device

migen/build/altera/quartus.py
When targeting CPLD devices, Quartus generates the bitstream as a POF
file instead of SOF. It is not necessary to convert it to RBF bitstream
format in that case.
=> build: quartus: prevent conversion to RBF when no SOF is generated

migen/build/platforms/arty_s7.py
Self-explanatory, this is mainly to keep feature-parity w/ LiteX; I forgot to make a PR for this.
Another PR will follow when OpenOCD support is added for Arty S7.
=> build/platforms: Add Arty S7 platform.

migen/build/platforms/sinara/sayma_amc.py
This is useful as a high-speed, unbuffered IO port for debugging.
=> Sayma AMC: add SYSCLK1_300

migen/build/platforms/tinyfpga_a.py
This pull request adds support for the (non-open) MachXO2-based `tinyfpga` A-series.
I don't expect this PR to be accepted as-is. MachXO2 is an odd FPGA in that it has an internal oscillator, and the board designer (cc: @tinyfpga) expects you to use the `OSCH` primitive to instantiate a default clock. Since this resource isn't provided by a pin, but each board is expected to provide a default clock, I improvised (read: created a hack) and created a subclassed `request` method to specifically handle the system clock without `migen.build.generic_platform.constraint_manager` allocating a pin. This way, methods of `GenericPlatform` that depend on `request` (such as `finalize`) still work, as intended without `resolve_signals` creating a fake pin constraint for a clock which is generated …
=> build/platforms: Add tinyfpga_a platform.

migen/fhdl/bitcontainer.py, migen/fhdl/structure.py, migen/fhdl/tools.py, migen/fhdl/verilog.py, migen/fhdl/visit.py, migen/genlib/fsm.py, migen/sim/core.py
This adds support for constant width variable offset slices called indexed part notation in verilog.
=> add indexed part select support

migen/build/lattice/icestorm.py
`nextpnr` (repo [here](https://github.com/YosysHQ/nextpnr)) will eventually be the default pnr backend for Project Icestorm. Since I'm currently using `nextpnr` to test some badly-behaving bitstreams generated by Migen*, I've added preliminary support for the pnr tool while keeping compatibility with `arcahne-pnr`, which is still the default.
* This is likely a timing violation that icetime isn't detecting properly and not Migen's fault.
=> lattice/icestorm: Add nextpnr as alternate pnr tool.

migen/build/lattice/programmer.py, migen/build/platforms/tinyfpga_bx.py
Self-explanatory, yet another platform to add :)! There is one more TinyFPGA platform I wish to add (EX-series), but it will need to wait until I have finished Diamond improvements and a finalized UCF.
`tinyprog` is technically a generic programmer that isn't tied to any vendor (but mostly works on Lattice parts currently). I eventually wish to move it into its own file like `openocd`, but am waiting for [certain features](https://github.com/tinyfpga/TinyFPGA-Bootloader/issues/20) to be implemented.
=> build/platforms: Add TinyFPGA BX board and programmer.

migen/build/platforms/ice40_hx8k_b_evn.py
I needed the SPI flash pins exposed to test some firmware, so I added them and verified they worked!
=> platforms/ice40_hx8k_b_evn: Add pins for spiflash io.

migen/sim/core.py
If an exception occurs during simulation, it is difficult to find out what user code provoked it from the traceback, which only shows the simulator code. This commit adds a print of the generator's current code location if the exception is raised while the simulator is evaluating a statement yielded from a generator. For example, trying to access a non-existent memory location will show the following:
```
While evaluating the following generator, an error occurred:
File mem_out_of_range_test.py, line 36, in gen_test
print((yield self.mem[adr]))
Traceback (most recent call last):
File "mem_out_of_range_test.py", line 65, in <module>
main()
File "mem_out_of_range_test.py", line 50, in main
run_simulation(dut, [dut.gen_test()], vcd_name="mem_out_of_range_test.vcd")
File …
```
=> give context when an exception is raised while evaluating a generator yield statement in simulation

migen/genlib/cdc.py
I believe this fixes issue #143
=> Fix issue where BusSynchronizer fails when iclock << oclock

migen/build/platforms/icebreaker.py
I/O is renamed to bring connector names more in line with what's already in Migen.
These changes have @esden's approval :).
=> platforms/icebreaker: Rename I/O w/ @esden's feedback.

migen/build/lattice/icestorm.py
regressed due to 5851076582323ef1acf24ba131f96ccaaea9d81e
=> fix yosys commands for build_names other than 'top'

migen/build/lattice/icestorm.py
It looks like the list has become out of date compared to the latest `chipdb-8k.txt` from icestorm. I haven't tested generation for all these packages but have for at least the `bg121` which didn't work before this patch and does afterwards.
=> Update list of valid packages for iCE40-HX8K

migen/fhdl/tracer.py
Add support for new opcode CALL_METHOD
https://docs.python.org/3/library/dis.html#opcode-CALL_METHOD
This makes the naming consistent between python 3.6 and 3.7
=> fhdl/tracer: support Python 3.7

migen/build/platforms/de0nanosoc.py
The eth_reset_n and eth_int_n pins were set to the same value of B14. I'm updating the pin of eth_reset_n to B4 as on the schematic. eth_int_n is correct.
=> Updating Pins of de0nanosoc.py Platform file

migen/build/platforms/upduino_v1.py
Adding initial support for upduino_v1 board. It has no external oscillator, so it has to use one of the internals.
This work is mainly based on what I found in build/platforms/tinyfpga_a.py for handling internal clock. 
In future one could add support for other hardware blocks like SPI, LFOSC or I3C.
=> build/platforms: add upduino_v1 board initial support

migen/fhdl/module.py, migen/fhdl/structure.py, migen/fhdl/verilog.py, migen/sim/core.py, migen/util/misc.py
Python 3.7 deprecated some fields in `collections`, most notably
`collections.Iterable`.  When run under Python 3.7, the interpreter
emits deprecation warnings, and notes that it will stop working entirely
under Python 3.8.
This patch replaces instances of `collections` with `collections.abc` as
necessary.
This patch fixes issue #175
=> migen: replace `collections` with `collections.abc` as necessary

migen/build/xilinx/ise.py
The command line is of the form;
```
-vlgincdir {"path1" "path2"}
```
Fixes the following error;
```
WARNING:Xst:3164 - Option "-vlgincdir" found multiple times in the command line. Only the first occurence is considered.
```
=> Fix `-vlgincdir` for xst.

migen/build/lattice/common.py
This patch is a basic implementation of `DifferentialInput` for Lattice iCE40 based on [TN1253](http://www.latticesemi.com/~/media/LatticeSemi/Documents/ApplicationNotes/UZ/UsingDifferentialIOLVDSSubLVDSiniCE40Devices.pdf).
Based on the discussion in #177, this is cumbersome to use with yosys/nextpnr because of the way the `SB_LVDS_INPUT` IO standard works. My understanding is that one needs to pass a dummy signal to `i_p` and make sure the corresponding `IOL_xA` resource is not requested / listed in the pcf. Is this correct? Is there an easy way to make the instantiation of `DifferentialInput` less error-prone?
=> Lattice iCE40: implement DifferentialInput

migen/build/lattice/common.py
This patch fixes the polarity of the `DifferentialInput` implementation for Lattice iCE40 platforms.
Although IMHO not very explicit in the docs (neither in [TN1253](http://www.latticesemi.com/~/media/LatticeSemi/Documents/ApplicationNotes/UZ/UsingDifferentialIOLVDSSubLVDSiniCE40Devices.pdf?document_id=47960) nor in the [technology library docs](http://www.latticesemi.com/~/media/LatticeSemi/Documents/TechnicalBriefs/SBTICETechnologyLibrary201504.pdf)), the output of `SB_IO` with `SB_LVDS_INPUT` IO standard is inverted. This however makes somehow sense since the `SB_IO` cell is passed the negative pin of the differential pair.
This behaviour was observed with nextpnr version YosysHQ/nextpnr@265fa1b and yosys version YosysHQ/yosys@ea8ac0aa.
=> Lattice iCE40: fix DifferentialInput polarity

migen/build/lattice/common.py
This patch reverts e43cd74 because of the underlying confusion between B=positive and A=negative pins, see [#181 (comment)](https://github.com/m-labs/migen/pull/181#issuecomment-489200088).
Moreover, the positive signal should be passed to `SB_IO`.
=> Fix iCE40 DifferentialInput

migen/build/altera/quartus.py
Generated script was lacking one newline, which caused bash error.
=> altera/quartus: fix generated build script

migen/build/platforms/ac701.py
This PR adds support for the Xilinx AC701 FPGA development board to migen.
It was derived from the KC705 platform and carefully adapted with with information from the schematic and user manual.
=> WIP: Platform support for the Xilinx AC701 FPGA development board

MANIFEST.in
These are needed to run the tests which are included in the sdists
=> Include examples in sdists

migen/fhdl/verilog.py
This PR adds support for integer attributes in Verilog as discussed in #189.
I was hesitant of testing it for `str` instead of `int` (`if isinstance(attr_value, str)`) but was afraid of edge cases with people using non str values (I'm not even sure if other types can be concatenated to str).
=> Add integer attributes

migen/build/xilinx/vivado.py
A stable order helps reproducability of the generated bitstream source code. This fix helps avoiding unnecessary rebuilds.
=> xilinx/vivado: emit sorted sources for top.tcl

migen/build/platforms/sinara/sayma_rtm2.py
Fixed Sayma RTM Basemod 1 amplifier control pins order for the sake of consistency with Basemod 0
=> Sayma RTM Basemod 1 amplifier An pin placement fix

migen/build/altera/quartus.py, migen/build/generic_platform.py, migen/build/generic_programmer.py, migen/build/lattice/diamond.py, migen/build/lattice/icestorm.py, migen/build/lattice/trellis.py, migen/build/tools.py, migen/build/xilinx/ise.py, migen/build/xilinx/platform.py, migen/build/xilinx/vivado.py
Makes sources self-contained
So far, usage has been added to only the `XilinxVivadoToolchain` because that one is relevant for Artiq. Shall we copy_sources_to_cwd() in all Migen platforms for consistency?
=> generic_platform: add copy_sources(), remove verilog_include_paths

migen/build/xilinx/common.py
I wanted to use a DDRInput on my Spartan6 board but there isn't an implementation in migen (which seems a little odd as there is a DDROutput). I noticed that LiteX had one so I copied it across. I think the licensing is compatible.
Not sure if there is some policy for merging stuff from LiteX, looks like they have added quite a bit of stuff to buiid/.
=> xilinx: add DDRInput for Spartan6

migen/fhdl/simplify.py
This PR forces specials of fragments processed by the `ModuleTransformer` subclasses in `migen.fhdl.simplify` to be sorted, thus ensuring that the order of creating new DUIDs remains the same when unrelated parts of the module to be synthesised have been changed.
There are subclasses of `migen.fhdl.decorators.ModuleTransformer`, namely `FullMemoryWE`, `MemoryToArray` and `SplitMemory`, that are defined in `migen.fhdl.simplify`, and each of them iterate over a Python set `f.specials` to replace or remove existing `Special`s. 
Sometimes, new `Special`s are instantiated while iterating the set, creating new DUIDs in the process. However, since Python set is unordered, the same order of creating the DUIDs is not guaranteed if any other parts of the module content has changed. 
In ARTIQ, the …
=> fhdl/simplify: sort specials before init-ing new DUID objects

migen/build/platforms/coraz7.py
They're quite similar but require different bitstream device names.
=> coraz7: rename to accomodate both hardware models

migen/build/platforms/zc706.py
Signal definition added to the platform, as specified in UG954. This should be the minimum necessary for implementing DRTIO support.
=> zc706 platform: add SFP and Si5324 signals

migen/build/platforms/kc705.py, migen/build/platforms/zc706.py
In DRTIO platform variants, there are slight differences in how GTX (used in KC705, ZC705 and Kasli-SoC) and GTP (used in Kasli) transceivers are defined and how they are passed to the interface.
This pull request is a part of three (this, nix-scripts and artiq) to bring the transceiver interface closer to reference (Kasli).
Migen part only changes the definitions of the signals to be identical in format with kasli/kasli-soc.
This PR should be merged in first.
=> Kc705/zc706 SFP signals changes

migen/build/platforms/sinara/kasli_soc.py
cdr_clk input signal in kasli_soc had defined iostandard of LVDS_18, but that is not an option in Vivado. Changed it to LVDS, as it should've been in the first place.
=> kasli_soc: cdr_clk: replaced lvds_18 with lvds_25

migen/build/platforms/sinara/kasli.py, migen/build/xilinx/vivado.py
Specify the `ExploreWithRemap` directive while optimizing the logic design in vivado.
Below is the description of the related directives in vivado 2021.1 (UG835):
```
ExploreArea - Run multiple passes of optimization, with an emphasis on reducing area.
ExploreWithRemap - Similar to ExploreArea but adds the remap optimization to compress logic levels.
AddRemap - Run the default optimization, and include LUT remapping to reduce logic levels.
```
=> vivado: improve timing during opt_design

migen/build/platforms/zc706.py
As mentioned here: https://git.m-labs.hk/M-Labs/artiq-zynq/issues/185 - LA26_P pin was "P28" but it should have been "R28".
=> zc706: la26_p pin fix
